ifndef::imagesdir[:imagesdir: ../images]

[[section-runtime-view]]
== Runtime View


ifdef::arc42help[]
[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...


.Further Information

See https://docs.arc42.org/section-6/[Runtime View] in the arc42 documentation.

****
endif::arc42help[]

=== <Full game>

This diagram represents a full game, from when the user logs to when the user ends the game

[plantuml,"Sequence diagram",png]
----
@startuml
actor User
participant WebApp
participant RustModule
database Db

User -> WebApp: Log in
WebApp -> Db: Checks credentials
Db --> WebApp: Returns data of the user
User -> WebApp: Selects board size, difficulty...
WebApp -> RustModule: Create board
RustModule --> WebApp: Board created
loop
    User -> WebApp: Plays their turn
    WebApp -> RustModule: Checks if there is a winner

    break There is a winner  
        RustModule --> WebApp: Returns result of the game
        WebApp --> User: Shows result of the gmae
    end

    WebApp -> RustModule: Asks the machine to play
    RustModule --> WebApp: Returns machine's play
    WebApp --> User: Shows what the machine has done
end
WebApp -> Db: Save data of the game
@enduml
----

=== <Asking for a hint>

This diagram represents the user asking for a hint

[plantuml,"Sequence diagram",png]

@startuml
actor User
participant WebApp
participant RustModule
database Db

User -> WebApp: Log in
WebApp -> Db: Checks credentials
Db --> WebApp: Returns data of the user
User -> WebApp: Selects board size, difficulty...
WebApp -> RustModule: Create board
RustModule --> WebApp: Board created

User -> WebApp: Asks for a hint
WebApp -> RustModule: Requests the hint
RustModule --> WebApp: Returns in YEN notation the movement hint
WebApp --> User: Returns the hint graphically

@enduml

=== <Runtime Scenario n>
